### ISSUE TITLE
Mastering Font checklist

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/festive#11]
#### Diacritics

<img width="1808" alt="Screen Shot 2023-07-06 at 18 00 07" src="https://github.com/googlefonts/festive/assets/48698976/1cf7842b-d951-404e-90a4-fe60c3490b56">

- [x] Adjust left and right sidebearings of all the comb marks to 0 (so that they are easy to edit)
- [x] Make sure the outlines are in the combining marks.
- [x] Inspect the design of marks is consistent with the font and among themselves  (in terms of balance, weight, size, and contrast). See the [Diacritics requirements](https://googlefonts.github.io/gf-guide/diacritics.html) section of the GF-Guide
    - [x] Ensure the diacritics consistency among related marks, [see issue of reference](https://github.com/googlefonts/italianno/issues/6). 
    - [x] `dotaccentcomb` is consistent with i and other dots in style (in Festive's case not be a spiral) and position.
    - [x] Inspect and balance the below marks (size, weight, balance) e.g. `ogonek` `cedilla` to avoid huge marks. e.g. above's `ccedilla`
    - [x] Test the comb marks by inspecting each of them in context (open the mark, right-click, and choose `Show all glyphs that use this glyph as a component` option).
    - [x] Adjust position using glyphs app locked guidelines.
    - [x] Decomposed transformed components, review proportions ensuring round coordinates + nodes at extremes
- [x] Make/Update composite glyphs for the entire font.
- [x] Delete the legacy marks and add them back so they are made using the combining marks as components.
- [x] Create combining `.case` marks by making them less tall and less narrow while keeping them at the same weight. Place them at the height they are intended to use, to be able to inspect them in their context.
- [x] Review and adjust the anchor's position.

#### Glyphs & Outlines

<img width="1212" alt="Screen Shot 2023-07-06 at 18 01 07" src="https://github.com/googlefonts/festive/assets/48698976/66b0e19a-9449-47cf-a1dd-222956f0b9db">

<img width="1726" alt="Screen Shot 2023-07-06 at 18 04 25" src="https://github.com/googlefonts/festive/assets/48698976/6e0f9bda-0e6c-45f3-a40a-ee67e7edff39">

<img width="548" alt="Screen Shot 2023-07-06 at 18 12 55" src="https://github.com/googlefonts/festive/assets/48698976/96b51f2a-0ce9-4609-a46b-edc74f4a4cff">

- [x] Inspect glyphs like `ae` `&` `@` have the right shape, size, weight, position
- [x] Inspect the ligatures coherence with the font (shape, spacing/kerning)
- [x] Numerals must be consistent with font design
- [x] Inspect/solve `fraction` consistency with the fractions. Adjust its sidebearings (negative).

#### Stylistic Sets
Review each Stylistic set ([see current GF font proof pdf](https://github.com/googlefonts/festive/blob/master/documentation/Proof-Festive-v1101-GFversion.pdf)) and ensure
- [x] There are no repeated shapes under different sets 
- [x] All the positional alternates are grouped in corresponding sets: `.fina` (for the ones with elongated ending strokes), `.init` (for the ones with elongated initial strokes) so those glyphs don't break the text line
- [x] Asigning a descriptive name for each feature. You can check the [Glyphs App Stylistic Sets tutorial](https://glyphsapp.com/learn/stylistic-sets)

**Comment by RobLeuschke** [comment]
All of the tasks have been completed. There are no init nor fina forms. In addition to the & @ and ae, the germandbls have been updated to be more consistent with the design. The numbers have been revised along with the superior forms and the fractions.
<img width="1207" alt="image" src="https://github.com/googlefonts/festive/assets/57553693/77a871d9-8fd1-4eda-8aa8-b927871910e6">
